# Generated by Django 3.2.16 on 2023-10-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_media_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Link:'),
        ),
    ]
